spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DatabaseUrl}
    password: ${password}
    username: ${userName}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none